apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: products-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: products
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70