apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
spec:
  replicas: 2
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
      - name: products
        image: jennyffernm/app-node-18:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: products-configmap
        resources:
            requests:
              cpu: 400m
